[package]
name = "gpu-test"
version = "0.1.0"
authors = ["Raph Levien <raph.levien@gmail.com>"]
description = "Empirical testing of GPU properties."
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies.piet-gpu-hal]
path = "../piet-gpu-hal"
